version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"
    ports:
      - "5000:5000"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    container_name: database-production
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  db-test:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    container_name: database-test
volumes:
  data:
